#include "listlinier.h"
#include "boolean.h"
#include "stdio.h"
#include "stdlib.h"
#include "Player.h"
#include "string.h"
#include "Block.h"
#include "MonopolyMap.h"
#include "gamelogic.h"
void player_travel(MonopolyMap map, PlayerAddress player,char* namatempat);
